<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style>
	.dat {
		border: 1px solid black;
		padding: 5px;
		margin-bottom: 5px;
	}

	span {
		width: 150px;
		display: block;
		float: left;
	}
	</style>
</head>
<body>
<?php if($showUploadForm):?>
<form enctype="multipart/form-data" action="import.php" method="POST">
<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
<select name="account">
  <option value="raiba_giro">Raiba Giro</option>
  <option value="hsbc_debit">HSBC Debit</option>
  <option value="hsbc_savings">HSBC Savings</option>
</select><br /><br />
Wähle eine Datei zum Hochladen aus: <input name="uploadedfile" type="file" /><br />
<input type="submit" value="Upload File" />
</form>
<?php else:?>
	<?php if($save):?>
		<?php echo $hits;?> Daten wurden gespeichert.
	<?php else:?>
		<?php echo $anzahlNeu;?> neue Datens&auml;tze.<br>
		<?php echo $angezeigteDatensaetze;?> angezeigte Datens&auml;tze.<br><br>
		<form method="post" action="import.php" id="content">
			<input type="hidden" name="filename" value="<?echo $target_path;?>" />
		<?php foreach($daten as $key => $dat):?>
			<div class="dat">
				<p><span>Bereits vorhanden:</span> <input type="checkbox" name="<?php echo $dat["id"]?>-vorhanden" value="vorhanden"></p>
				<p><span>Datum:</span> <input type="text" name="<?php echo $dat["id"]?>-datum" value="<?php echo $dat[getBuchungstag()]?>"></p>
				<p><span>Umsatz:</span> <?php echo $dat[getUmsatz()]?></p>
				<p><span>Geldfluss:</span> <?php if($dat["SH"]=="S")echo"Ausgaben";else echo "Einnahmen";?></p>
				<p><span>Verwendungszweck:</span>  <textarea name="<?php echo $dat["id"]?>-neuerverwendungszweck" cols="30" rows="5"><?php echo $dat[getEmpfaenger()]." ".$dat[getVerwendungszweck()];?></textarea></p>
				<?php echo $dat["kategorieContent"]?>
			</div>
		<?php endforeach;?>
			<input type="submit" name="save">
		</form>
	<?php endif;?>
<?php endif;?>
</body>
</html>